spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:app

  jpa:
    generate-ddl: true
    show-sql: true
  ddl-auto: create-drop

  h2:
    console:
      enabled: true


server:
  port: 8071